### ISSUE TITLE
Start using supervisord instead of spawner.dart

### ISSUE THREAD

**Issue by ThomasLocke** [Bitstackers/ServerStack#26]
http://supervisord.org/

**Comment by rostgaard** [comment]
I've performed some initial tests on managing the FreeSWITCH processes from supervisord[1], and it seems very promising. To be able to run our stack servers individually, however, we need a shared secret between them to allow IPC. I'll open a new issue for tracking this.

[1]http://stackoverflow.com/questions/25419214/how-to-configure-supervisord-for-freeswitch
