### ISSUE TITLE
REST interface for contact@reception endpoints

### ISSUE THREAD

**Issue by ThomasLocke** [Bitstackers/ServerStack#28]
A simple list of strings would do just fine, such as ['thomas@domain','foo@bar','22334455'].

**Comment by rostgaard** [comment]
See
https://github.com/Bitstackers/ServerStack/blob/master/lib/contact_server/router.dart#L79
https://github.com/Bitstackers/ServerStack/blob/master/lib/contact_server/router.dart#L80
For REST API syntax.
