### ISSUE TITLE
"Cron job" to delete old calendar entries

### ISSUE THREAD

**Issue by ThomasLocke** [Bitstackers/ServerStack#31]
Calendar entries with stop timestamps in the past should be deleted in a batch job at night, so they don't clutter the interface the day after.

And always remember that anything done at all with calendars must be logged, logged and logged some more. It is an area that is plagued by mistakes, and very often users need to figure who wrote what where and when.

Have we already got a plan for this @rostgaard ?

**Comment by rostgaard** [comment]
The initial plan was to implement the cleanup procedure from current system - manual. After a beta test we can build a small script that archives the entries based on current time.

As for logging, we can create a new table in the database with this information.

I've tagged this as being a post-beta-test feature as it is, as I've understood it, not essential for a technically functional system.

**Comment by rostgaard** [comment]
The logging is discussed further at: https://github.com/Bitstackers/OpenReceptionFramework/issues/4
