### ISSUE TITLE
CORS header trouble

### ISSUE THREAD

**Issue by ThomasLocke** [Bitstackers/ServerStack#34]
Method DELETE is not allowed by Access-Control-Allow-Methods....

Verified to be a problem with calendar related calls.

ARGH!

**Comment by rostgaard** [comment]
Forgot to add issue ID to this commit 501db946d3881443dc81862fd14a6721bf97df69

**Comment by rostgaard** [comment]
I think all the servers that needs additional methods are patched up to use shelf instead of our implementation. One exception, however, would be the management server that needs general love. I think we will cross that road when we get to it, and just close this issue for now.
